export default [['Hunting calls', '#a6cee3'],
  ['Disaster ballads', '#1f78b4'],
  ['Bawdy songs', '#FF1654'],
  ['War songs', '#33a02c'],
  ['Schottisches', '#fb9a99'],
  ['Drinking songs', '#e31a1c'],
  ['Marches', '#fdbf6f'],
  ['Animal calls', '#ff7f00'],
  ['Humorous recitations', '#cab2d6'],
  ['Courting songs', '#a6d854'],
  ['Tall tales', '#ffff99'],
  ['Waltzes', '#b15928'],
  ['Counting songs', '#a6d854'],
  ['Love songs', '#f768a1'],
  ['Hunting songs', '#bebada'],
  ['Prayers', '#cb181d'],
  ['Narratives', '#ffcc00'],
  ['Folk drama', '#bf812d'],
  ['Religious drama', '#fb6a4a'],
  ['Hymns', '#99000d'],
  ['Humorous songs', '#FE9000'],
  ['Announcements', '#ffffbf'],
  ['Field hollers', '#44CFCB'],
  ['Nursery rhymes', '#41ab5d'],
  ['Cowboy songs', '#D4B483'],
  ['Corridos', '#f6e8c3'],
  ['Fiddle tunes', '#a50f15'],
  ['Lullabies', '#b2df8a'],
  ['Spoken word', '#ffff99'],
  ['Dance music', '#FCAB64'],
  ['Ballads', '#dfc27d'],
  ['Work songs', '#01A7C2'],
  ['Children\'s songs', '#61E786'],
  ['Religious songs', '#D81159']]
